### ISSUE TITLE
Move 2024 Enum support - timeline

### ISSUE THREAD

**Issue by fl0ydj** [kunalabs-io/sui-client-gen#13]
Hey @kklas,
seems like enums are on testnet now with some breaking changes for this library as well.

As sui client gen is now a core part of our stack, whats your current thinking about the timeline of integrating them?
Of course understand that you must be busy with a lot of other things as well :)

Justin

**Comment by kklas** [comment]
Hey, my immediate goal is to upstream the tool to the sui repo and mysten will take it from there.

**Comment by fl0ydj** [comment]
Ok thanks! Whats the timeline for this? Who could I talk to about this from the mysten team?

**Comment by fl0ydj** [comment]
Thanks! Closing this then in favor of https://github.com/MystenLabs/sui/pull/15984#issuecomment-2087355980
