### ISSUE TITLE
upgrade to sui latest SDK version

### ISSUE THREAD

**Issue by Jarekkkkk** [kunalabs-io/sui-client-gen#14]
Hi team, since Sui has upgraded previous SDK 

can you migrate the supported SDK from `@mysten/sui.js` to `@mysten/sui`?

https://sdk.mystenlabs.com/typescript/migrations/sui-1.0

thanks in advance !

**Comment by kklas** [comment]
This was fixed by 9b432567225c97e34f5c322066adb725cfde19a8
