### ISSUE TITLE
How to create vector<T> from bcs?

### ISSUE THREAD

**Issue by shiqicao** [kunalabs-io/sui-client-gen#15]
`VectorClassReified` doesn't have `fromBcs`, how can I create a vector from bcs?

**Comment by kklas** [comment]
Well spotted! I've fixed this in 3eff78af7ce7e1568381004bbea51b7d25f5729a. You should now be able to do:

```ts
const reified = vector('u64') // or Vector.r('u64')
reified.fromBcs(...)
```

Let me know if you run into any issues!
