### ISSUE TITLE
TypeScript errors

### ISSUE THREAD

**Issue by juzybits** [kunalabs-io/sui-client-gen#6]
Code generation works, but `tsc` shows some TypeScript errors on the generated code: [tsc_output.txt](https://github.com/kunalabs-io/sui-client-gen/files/13259941/tsc_output.txt)

The errors are mostly:
`error TS2305: Module '"@mysten/bcs"' has no exported member 'Encoding'.`
And some type mismatches:
`Type '...' is not assignable to type '...'`

I'm using the latest Sui binary and the latest TS library:
`sui 1.13.0-64fe2b6871`
`@mysten/sui.js@0.45.1`

**Comment by kklas** [comment]
fixed in 66d27f195d8c4570d6b6d518d29e12acb8679ae9
